---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - dihmandrake
  assignees:
  - dihmandrake
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - dihmandrake
  assignees:
  - dihmandrake
