---
name: Auto Merge
on:
  pull_request_target:
    # Explictly state the default types we want to act upon
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # Keeping the metadata here as it validates the commit signature
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve PR
        run: gh pr review --approve --body "Auto Approve PR via Action as the Pull Request was opended by dependabot" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for PR
        run: gh pr merge --auto --delete-branch --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  owner-auto-approve:
    name: Repo owner auto approve
    runs-on: ubuntu-latest
    if: ${{ github.actor_id == github.repository_owner_id }}
    steps:
      - name: Approve PR
        run: gh pr review --approve --body "Auto Approve PR via Action as the Pull Request was opended by the repository owner" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
