---
name: Publish Container Image
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-container:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Setup Cache for Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      - name: Set up QEMU for Multi Arch builds
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx for Multi Arch builds and Caching
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event.repository.default_branch == github.ref_name }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: "ghcr.io/${{ github.repository }}"

      - name: Build Docker image & push on main branch
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: ${{ github.event.repository.default_branch == github.ref_name }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

# Issue with Matrix builds. The manifest is not created correctly.
# Need to push artifacts around, merge into manifest and then push
#jobs:
#  push_to_registry:
#    name: Build and push Docker image to Docker Hub
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        platform: [ linux/amd64, linux/arm/v7, linux/arm64/v8 ]
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#        with:
#          persist-credentials: false
#          submodules: true
#      - name: Setup Cache for Docker layers
#        uses: actions/cache@v3
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ matrix.platform }}-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-${{ matrix.platform }}-
#      - name: Set up QEMU for Multi Arch builds
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx for Multi Arch builds
#        uses: docker/setup-buildx-action@v2
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build & Push to Docker Hub
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          platforms: ${{ matrix.platform }}
#          tags: "${{ secrets.DOCKER_USERNAME }}/strongswan:latest
#            ,${{ secrets.DOCKER_USERNAME }}/strongswan:${{ github.sha }}"
#          cache-from: type=local,src=/tmp/.buildx-cache
#          cache-to: type=local,dest=/tmp/.buildx-cache
