---
name: Publish Docker image
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm/v7, linux/arm64/v8 ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Setup Cache for Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.platform }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform }}-
      - name: Set up QEMU for Multi Arch builds
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx for Multi Arch builds
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: "${{ secrets.DOCKER_USERNAME }}/strongswan:latest
            ,${{ secrets.DOCKER_USERNAME }}/strongswan:${{ github.sha }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
