---
name: "Syntax and Lint"

on: [push]

permissions:
  contents: read
  statuses: write

jobs:
  Super-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: GitHub Super Linter
        uses: github/super-linter@v4.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE: false  # To many false positives and issues
          #VALIDATE_DOCKERFILE_HADOLINT: true  # Explicitly enabled to show Dockerfile linting;
