---
name: Update git submodules

on:
  #schedule:
  #  - cron:  '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Update-all-submodules:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
        fetch-depth: 0
        submodules: true
    - name: Configure git
      run: |
        git config --global user.name "Jasper Bernhardt"
        git config --global user.email "jasper.bernhardt@live.de"
        git remote set-url --push origin "https://dihmandrake:$GITHUB_TOKEN@github.com/dihmandrake/strongswan-container"
    - name: Update submodules
      run: |
        git submodule foreach '../.ci/update-to-latest-git-tag.sh'
    - name: Commit & Push if changed
      run: |
        if git commit -am "Update submodules"; then git push; fi
