---
name: Update git submodules

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Update-all-submodules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
        fetch-depth: 0
        submodules: true
    - name: Update submodules
      run: |
        git submodule foreach '../.ci/update-to-latest-git-tag.sh'
    - name: Commit & Push if changed
      run: |
        if git commit -am "Update submodules"; then git push; fi
